export const pesudoProductData = [
  {
    id: 101,
    product_name: "Skinny Fit Jeans",
    brand_name: "Levi's",
    price: 3299,
    rating: 4.5,
  },
  {
    id: 102,
    product_name: "Graphic T-Shirt",
    brand_name: "Puma",
    price: 999,
    rating: 4.3,
  },
  {
    id: 103,
    product_name: "Floral Print Dress",
    brand_name: "Biba",
    price: 2499,
    rating: 4.4,
  },
  {
    id: 104,
    product_name: "Casual Shirt",
    brand_name: "Allen Solly",
    price: 1799,
    rating: 4.2,
  },
  {
    id: 105,
    product_name: "Cotton Kurta",
    brand_name: "FabIndia",
    price: 2299,
    rating: 4.6,
  },
  {
    id: 106,
    product_name: "Denim Jacket",
    brand_name: "Wrangler",
    price: 3999,
    rating: 4.5,
  },
  {
    id: 107,
    product_name: "Athletic Shorts",
    brand_name: "Adidas",
    price: 1299,
    rating: 4.3,
  },
  {
    id: 108,
    product_name: "Polo T-Shirt",
    brand_name: "U.S. Polo Assn.",
    price: 1499,
    rating: 4.4,
  },
  {
    id: 109,
    product_name: "Chinos",
    brand_name: "Peter England",
    price: 1899,
    rating: 4.2,
  },
  {
    id: 110,
    product_name: "Casual Blazer",
    brand_name: "Raymond",
    price: 5499,
    rating: 4.5,
  },
  {
    id: 111,
    product_name: "Formal Trousers",
    brand_name: "Van Heusen",
    price: 2499,
    rating: 4.3,
  },
  {
    id: 112,
    product_name: "Ethnic Lehenga",
    brand_name: "Bombay Selection",
    price: 5999,
    rating: 4.6,
  },
  {
    id: 113,
    product_name: "Activewear Leggings",
    brand_name: "Nike",
    price: 2199,
    rating: 4.4,
  },
  {
    id: 114,
    product_name: "Embroidered Saree",
    brand_name: "Sabyasachi",
    price: 12999,
    rating: 4.8,
  },
  {
    id: 115,
    product_name: "Formal Suit",
    brand_name: "Louis Philippe",
    price: 7999,
    rating: 4.7,
  },
  {
    id: 116,
    product_name: "Summer Dress",
    brand_name: "H&M",
    price: 1599,
    rating: 4.2,
  },
  {
    id: 117,
    product_name: "Sweatshirt",
    brand_name: "Forever 21",
    price: 1299,
    rating: 4.1,
  },
  {
    id: 118,
    product_name: "Printed Skirt",
    brand_name: "Global Desi",
    price: 1899,
    rating: 4.3,
  },
  {
    id: 119,
    product_name: "Slim Fit Jeans",
    brand_name: "Pepe Jeans",
    price: 2799,
    rating: 4.4,
  },
  {
    id: 120,
    product_name: "Boho Top",
    brand_name: "Madame",
    price: 1199,
    rating: 4.2,
  },
  {
    id: 121,
    product_name: "Track Pants",
    brand_name: "Reebok",
    price: 1499,
    rating: 4.3,
  },
  {
    id: 122,
    product_name: "Woolen Sweater",
    brand_name: "Monte Carlo",
    price: 2599,
    rating: 4.5,
  },
  {
    id: 123,
    product_name: "Ethnic Jacket",
    brand_name: "W for Women",
    price: 2999,
    rating: 4.4,
  },
  {
    id: 124,
    product_name: "Party Dress",
    brand_name: "Manish Malhotra",
    price: 9999,
    rating: 4.7,
  },
  {
    id: 125,
    product_name: "Casual Jumpsuit",
    brand_name: "The Label Ritu Kumar",
    price: 3499,
    rating: 4.5,
  },
  {
    id: 126,
    product_name: "Linen Shirt",
    brand_name: "Mufti",
    price: 1899,
    rating: 4.2,
  },
  {
    id: 127,
    product_name: "Printed Kurti",
    brand_name: "Aurelia",
    price: 1299,
    rating: 4.3,
  },
  {
    id: 128,
    product_name: "Denim Skirt",
    brand_name: "Calvin Klein",
    price: 3499,
    rating: 4.6,
  },
  {
    id: 129,
    product_name: "Formal Blouse",
    brand_name: "AND",
    price: 1599,
    rating: 4.4,
  },
  {
    id: 130,
    product_name: "Casual Pants",
    brand_name: "Westside",
    price: 1799,
    rating: 4.2,
  },
];
